CREATE TABLE MANAGES (
    EmployeeID INT NOT NULL,
    InventoryBookID INT NOT NULL,
    FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (InventoryBookID) REFERENCES INVENTORY(InventoryBookID) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (EmployeeID, InventoryBookID)
);