CREATE TABLE ORDER_DETAILS (
    OrderID INT NOT NULL,
    BookID INT NOT NULL,
    Price DECIMAL(10, 2),
    Quantity INT,
    FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (BookID) REFERENCES BOOK(BookID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT ORDER_DETAILS_price CHECK (Price > 0),
    CONSTRAINT ORDER_DETAILS_quantity CHECK (Quantity > 0),
    PRIMARY KEY (OrderID, BookID)
);