CREATE TABLE WRITE (
    AuthorID INT NOT NULL,
    BookID INT NOT NULL,
    FOREIGN KEY (AuthorID) REFERENCES AUTHOR(AuthorID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (BookID) REFERENCES BOOK(BookID) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (AuthorID, BookID)
);