CREATE TABLE INVENTORY (
    InventoryBookID INT PRIMARY KEY,
    RestockThreshold INT,
    StockQuantity INT CHECK (StockQuantity >= 0),
    BookID INT NOT NULL UNIQUE,
    FOREIGN KEY (BookID) REFERENCES BOOK(BookID) ON DELETE CASCADE ON UPDATE CASCADE
);