CREATE TABLE INVENTORY (
    InventoryBookID INT UNIQUE NOT NULL,
    RestockThreshold INT,
    StockQuantity INT,
    BookID INT NOT NULL,
    PRIMARY KEY (InventoryBookID, BookID),
    FOREIGN KEY (BookID) REFERENCES BOOK(BookID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT INVENTORY_stock CHECK (StockQuantity >= 0)
);